---
#### NOTE: Only tested on Ubuntu 1604. Should work with minimal changes on any Linux based system, especially debian derivations - package names may differ for RHEL based systems.
- hosts: localvagrant
  become: yes
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
  handlers:
    - name: restart zen
      service: name=zend state=restarted

  tasks:
    - name: update hostname
      hostname: 
        name: '{{ hostname }}'
      
      # create users
    - name: Create group(s)
      group:
        name: '{{ group }}'

    - name: Create users context, sftpguy, sftpuser, cms, dms, dmstest
      user:
        groups: '{{ group }}'
        append: True
        name: '{{ item }}'
      with_items:
        - nodeeu

    # sudo fallocate -l 4G /swapfile
    # Do SWAP
    - name: check if swap file exists
      stat:
        path: "{{ swap_file }}"
      register: swap_file_check
      when: not swap_file_check.stat.exists

    - name: allocate space
      command: fallocate -l 4G {{ swap_path }}
      become: yes

    - name: chmod swap
      command: chmod 600 {{ swap_path }}
      become: yes

    - name: made swap
      command: mkswap {{ swap_path }}
      become: yes

    - name: turn swap on
      command: swapon {{ swap_path }}
      become: yes

    - name: edit fstab to keep swap
      shell: | 
          cat <<EOF >> /etc/fstab
          /swapfile none swap sw 0 0
          EOF
      become: yes

    - name: change swappiness
      shell: |
        cat <<EOF >> /etc/sysctl.conf
        vm.swappiness=10
        EOF
      become: yes

    - name: "Install utils and dependencies"
      apt: "name={{ item }} state=present"
      with_items:
        - pwgen
        - sudo
        - git
        - npm
        - lynx
        - curl
        - unzip
        - ufw
        - exim4
        - ntp
        - fail2ban
        - clamav
        - socat
        - libapache2-mpm-itk
        - rkhunter
        - rsnapshot
        - heirloom-mailx
        - snmp
        - snmpd
        - libsnmp-dev
        - apt-transport-https 
        - lsb-release


    # Install Zen
    # - name: turn swap on
    #   command: 'deb https://zencashofficial.github.io/repo/ '$(lsb_release -cs)' main' | tee --append /etc/apt/sources.list.d/zen.list
    #   become: yes

    - apt_repository:
        repo: deb-src https://zencashofficial.github.io/repo 
        state: present
      become: yes


    - name: gpg --keyserver ha.pool.sks-keyservers.net
      command: gpg --keyserver ha.pool.sks-keyservers.net --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669
      become: yes

    - name: gpg --export
      command: gpg --export 219F55740BBF7A1CE368BA45FB7053CE4991B669 | sudo apt-key add -
      become: yes
    
    - name: Update apt cache if needed...
      apt: update_cache=yes cache_valid_time=3600

    - name: "Install zen packages"
      apt: "name={{ item }} state=present"
      with_items:
        - zen

    - name: zen-fetch-params
      command: zen-fetch-params
    
    # Update the Zen Configuration File
    - name: Update the Zen Configuration File
      template:
        src: "templates/.zen/zen.conf"
        dest: "~/.zen/zen.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart zen

    - name: run acme.sh
      shell: |
        cd 
        git clone https://github.com/Neilpang/acme.sh.git
        cd acme.sh
        ./acme.sh --install
        sudo ~/.acme.sh/acme.sh --issue --standalone -d {{ hostname }} 

    - name: Do Crons
      cron: 
        name: "Run Clamscan"
        user: "root"
        minute: "0"
        hour: "22"
        job: "/root/ClamByDay.sh > /dev/null"

    - name: ssl cron
      cron: 
        user: "root"
        minute: "6"
        hour: "1"
        job: "/home/{{ user }}/.acme.sh/acme.sh --cron --home /home/{{ user }}/.acme.sh > /dev/null"
        name: "Let's Encrypt Renewal"

    # - name: get certs
    #   shell: |
    #     sudo cp /home/{{ user }}/.acme.sh/{{ hostname }}/ca.cer /usr/share/ca-certificates/ca.crt
    #     sudo dpkg-reconfigure ca-certificates

    # - name: update cert locations in zen.conf
    #   shell: |
    #     zen-cli stop
    #     cat <<EOF >> ~/.zen/zen.conf
    #     tlscertpath=/home/{{ user }}/.acme.sh/{{ hostname }}/{{ hostname }}.cer 
    #     tlskeypath=/home/{{ user }}/.acme.sh/{{ hostname }}/{{ hostname }}.key
    #     EOF
    #   notify: restart zen
    
    # - name: get tracker
    #   shell: |
    #     mkdir ~/zencash
    #     cd ~/zencash
    #     git clone https://github.com/ZencashOfficial/secnodetracker.git
    #     cd secnodetracker
    #     npm install
    #     node setup.js

    # - name: install pm2
    #   npm: 
    #     name: pm2 

    # - name: start tracker
    #   command: pm2 start app.js --name securenodetracker

    # - name: add tracker to startup
    #   command: pm2 startup
 

    ####### UFW
    - name: add ssh
      ufw:
        rule: allow
        name: OpenSSH
      become: yes

    # - name: add ports
    #   ufw:
    #     rule: allow
    #     port: '{{ item }}'
    #     proto: tcp
    #     with items:
    #       - 22
    #       - 25
    #       - 110
    #       - 80
    #       - 443
    #       - 3306
    #       - 161

    # - name: Configure basic UFW behaviour
    #   ufw:
    #     state: enabled
    #     policy: deny
